image: rocker/tidyverse

stages:
  - test
  - deploy


# To have the coverage percentage appear as a gitlab badge follow these
# instructions:
# https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
# The coverage parsing string is
# Coverage: \d+\.\d+

testing:
    stage: test
    allow_failure: true
    when: on_success
    only:
        - master
    script:
      - R -e "remotes::install_deps(dependencies = TRUE,repos='https://packagemanager.rstudio.com/all/latest')"
      - R -e "testthat::test_file('tests/shinytest/manual_test_dl.R')"

    artifacts:
        paths:
            - public


onshinyapps:
    stage: deploy
    dependencies:
        - testing
    script:
        - ls
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master
