image: rocker/tidyverse

stages:
  - setup
  - test_manual_dl
  - test_interaction_tableau


# To have the coverage percentage appear as a gitlab badge follow these
# instructions:
# https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
# The coverage parsing string is
# Coverage: \d+\.\d+

install_test:
  stage: setup
  only:
      - master
  script:
      - sudo apt-get update -y
      - sudo apt-get install -y libudunits2-dev
      - Rscript install_deps.R
      - Rscript run_tests.R

