image: rocker/tidyverse

stages:
  - setup_and_test


# To have the coverage percentage appear as a gitlab badge follow these
# instructions:
# https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
# The coverage parsing string is
# Coverage: \d+\.\d+
# sudo git clone https://github.com/phileas-condemine/Zonage_ARS.git

install_test:
  stage: setup_and_test
  only:
      - master
  script:
      - sudo add-apt-repository -y ppa:cran/poppler
      - sudo apt-get update -y
      - sudo apt-get install -y libudunits2-dev
      - sudo apt-get install -y libgdal-dev
      - sudo apt-get install -y gdal-bin
      - sudo apt-get install -y libgeos-dev
      - sudo apt-get install -y libproj-dev
      - sudo apt-get install -y libpoppler-cpp-dev
      - Rscript install_deps.R
      - R -e "webshot::install_phantomjs()"
      - base64 $DROPTOKEN -d > droptoken.rds
      - cp $gm_credentials credentials.json
      - mkdir .secrets
      - base64 $GMSECRET -d > .secrets/$PATHGMSECRET
      - mkdir data
      - mkdir tests/shinytest/snapshot-current
      - Rscript run_tests.R

