image: rocker/tidyverse

stages:
  - test
  - deploy


# To have the coverage percentage appear as a gitlab badge follow these
# instructions:
# https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
# The coverage parsing string is
# Coverage: \d+\.\d+

testing:
    stage: test
    only:
        - master
    script:
     - sudo apt-get update -y
     - sudo apt-get install -y libudunits2-dev
     - Rscript R/install_deps.R
      - R -e "testthat::test_file('tests/shinytest/manual_test_dl.R')"

    artifacts:
        paths:
            - public


onshinyapps:
    stage: deploy
    dependencies:
        - testing
    script:
        - ls
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master
