image: rocker/tidyverse

stages:
  - setup
  - test_manual_dl
  - test_interaction_tableau


# To have the coverage percentage appear as a gitlab badge follow these
# instructions:
# https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
# The coverage parsing string is
# Coverage: \d+\.\d+

install_test:
  stage: setup
  only:
      - master
  script:
      - sudo apt-get update -y
      - sudo apt-get install -y libudunits2-dev
      - Rscript R/install_deps.R
      - R -e "testthat::test_file('tests/shinytest/manual_test_dl.R')"
      - R -e "testthat::test_file('tests/shinytest/interaction_w_tableau_zonage.R')"
